version: '3'
volumes:
  psql:


services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ridefinder
    healthcheck:
      test: pg_isready -U postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5432:5432
    volumes:
      - psql:/var/lib/postgresql/data
